extends Node2D

# Maze Game - Generated by Vector AI

var score = 0
var total_coins = 0

func _ready():
	# Count total coins in the level
	total_coins = get_tree().get_nodes_in_group("coins").size()
	$UI/ScoreLabel.text = "Score: 0/" + str(total_coins)

func collect_coin():
	score += 1
	$UI/ScoreLabel.text = "Score: " + str(score) + "/" + str(total_coins)

	if score >= total_coins:
		$UI/WinLabel.visible = true
