extends CharacterBody2D

# Player script - Generated by Vector AI

const SPEED = 300.0

func _physics_process(delta):
	# Get input direction
	var direction = Input.get_vector("ui_left", "ui_right", "ui_up", "ui_down")

	# Set velocity
	velocity = direction * SPEED

	# Move and slide
	move_and_slide()

	# Check for coin collisions
	for i in get_slide_collision_count():
		var collision = get_slide_collision(i)
		var collider = collision.get_collider()

		if collider.is_in_group("coins"):
			collider.queue_free()
			get_parent().collect_coin()
